set(_AMENT_PACKAGE_NAME "general_box_detector_ros")
set(general_box_detector_ros_VERSION "0.1.0")
set(general_box_detector_ros_MAINTAINER "vtol <vtol@localhost.local>")
set(general_box_detector_ros_BUILD_DEPENDS "rclcpp" "geometry_msgs" "sensor_msgs" "std_msgs" "tf2_ros" "visualization_msgs" "cv_bridge" "rcl_interfaces")
set(general_box_detector_ros_BUILDTOOL_DEPENDS "ament_cmake")
set(general_box_detector_ros_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "sensor_msgs" "std_msgs" "tf2_ros" "visualization_msgs" "cv_bridge" "rcl_interfaces")
set(general_box_detector_ros_BUILDTOOL_EXPORT_DEPENDS )
set(general_box_detector_ros_EXEC_DEPENDS "launch" "launch_ros" "ament_index_python" "rviz2" "rclcpp" "geometry_msgs" "sensor_msgs" "std_msgs" "tf2_ros" "visualization_msgs" "cv_bridge" "rcl_interfaces")
set(general_box_detector_ros_TEST_DEPENDS )
set(general_box_detector_ros_GROUP_DEPENDS )
set(general_box_detector_ros_MEMBER_OF_GROUPS )
set(general_box_detector_ros_DEPRECATED "")
set(general_box_detector_ros_EXPORT_TAGS)
list(APPEND general_box_detector_ros_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
