<?xml version="1.0"?>
<package format="3">
  <name>general_box_detector_ros</name>
  <version>0.1.0</version>
  <description>ROS 2 image publisher for the GeneralBox Hailo YOLO detector.</description>
  <maintainer email="vtol@localhost.local">vtol</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>rcl_interfaces</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
